[project]
authors = ["liuzhao1225 <liuzhao1225@gmail.com>"]
channels = ["pytorch", "nvidia", "conda-forge"]
description = "Add a short description here"
name = "YouDub-webui"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
loguru = ">=0.7.2,<0.8"
yt-dlp = ">=2024.8.6,<2025"
scipy = ">=1.14.1,<2"
openai = ">=1.59.0,<2"
librosa = ">=0.10.2.post1,<0.11"
python = "<3.12"
pip = ">=24.3.1,<25"
pytorch = ">=2.5.1,<3"
torchvision = ">=0.20.1,<0.21"
torchaudio = ">=2.5.1,<3"
pytorch-cuda = "12.1.*"
cudnn = "<9"

[pypi-dependencies]
bilibili-toolman = ">=1.0.7.9, <2"
audiostretchy = ">=1.3.5, <2"
whisperx = { git = "https://github.com/mokurin000/whisperx.git" }
demucs = { git = "https://github.com/mokurin000/demucs.git" }
gradio = "*"
python-dotenv = ">=1.0.1, <2"
