[project]
name = "youdub"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"

# must install via pixi
dependencies = []

[tool.setuptools]
py-modules = ["youdub"]
